import { Rank } from '@prisma/client';
import { DDragon } from '@fightmegg/riot-api';

const ddragon = new DDragon();
const SkinLines = [
  'Academy',
  'Bilgewater: Burning Tides',
  'Bilgewater: Mercs',
  'Chronicle',
  'Curse of the Void',
  'Freljord',
  'Otherroads',
  'Ruination',
  'Traditional',
  'Anima Squad',
  'Arcade: Battle Boss',
  'Arcade: Heroes',
  'Demacia Vice',
  'Arcana',
  'Arcane',
  'Arcanists',
  'Arclight',
  'Justicar',
  'Ashen Knights',
  'Battle Queens',
  'Battlecast',
  'Heartbreakers',
  'Bees!',
  'Beta',
  'Blackfrost',
  'Bloodstone',
  'Cafe Cuties',
  'Cats Versus Dogs',
  'Shockblade',
  "Collector's Edition",
  'Cottontail',
  'Crime City',
  'Crime City Nightmare',
  'Debonair',
  'Crimson Elite',
  'Crystal Rose',
  'Withered Rose',
  'Culinary Masters',
  'Bilgewater: Curse of the Drowned',
  'Death Sworn',
  'Definitely Not',
  'Demonic',
  'Dragon World',
  'Dreadknights',
  'Coven',
  'Death Blossom',
  'Eclipse',
  'Elderwood',
  'Omen of the Dark',
  'Elementalist',
  'Challenger',
  'Conqueror',
  'World Champions: 2011',
  'World Champions: 2012',
  'World Champions: 2013',
  'World Champions: 2014',
  'World Champions: 2015',
  'World Champions: 2016',
  'World Champions: 2017',
  'World Champions: 2018',
  'World Champions: 2019',
  'World Champions: 2020',
  'World Champions: 2021',
  'World Championship',
  'Cosmic',
  'Dark Star',
  'Fables',
  'Papercraft',
  'Forgotten Depths',
  'Dragonmancers',
  'Phoenixmancers',
  'Galactic',
  'Glacial',
  'Battle Academia',
  'Guardian of the Sands',
  'Pharaoh',
  'Headhunter',
  'Heartbreakers',
  'Heavy Metal',
  'Hextech',
  'High Noon',
  'Road Warrior',
  'Vandal',
  'Three Honors',
  'Immortal Journey',
  'Infernal',
  ''
] as const;

type SkinLine = typeof SkinLines[number];

export const skinToSkinLineMapping: Record<string, SkinLine> = {};

// export const skinToSkinTierMapping: Record<string, SkinTier> = {}

// export const skinTierToSkinMapping: Record<SkinTier, string> = {};
